ironclad_cards = [
    "Bash",
    "Defend_R",
    "Strike_R",
    "Anger",
    "Armaments",
    "Body Slam",
    "Clash",
    "Cleave",
    "Clothesline",
    "Flex",
    "Havoc",
    "Headbutt",
    "Heavy Blade",
    "Iron Wave",
    "Perfected Strike",
    "Pommel Strike",
    "Shrug It Off",
    "Sword Boomerang",
    "Thunderclap",
    "True Grit",
    "Twin Strike",
    "Warcry",
    "Wild Strike",
    "Battle Trance",
    "Blood for Blood",
    "Bloodletting",
    "Burning Pact",
    "Carnage",
    "Combust",
    "Dark Embrace",
    "Disarm",
    "Dropkick",
    "Dual Wield",
    "Entrench",
    "Evolve",
    "Feel No Pain",
    "Fire Breathing",
    "Flame Barrier",
    "Ghostly Armor",
    "Hemokinesis",
    "Infernal Blade",
    "Inflame",
    "Intimidate",
    "Metallicize",
    "Power Through",
    "Pummel",
    "Rage",
    "Rampage",
    "Reckless Charge",
    "Rupture",
    "Searing Blow",
    "Second Wind",
    "Seeing Red",
    "Sentinel",
    "Sever Soul",
    "Shockwave",
    "Spot Weakness",
    "Uppercut",
    "Whirlwind",
    "Barricade",
    "Berserk",
    "Bludgeon",
    "Brutality",
    "Corruption",
    "Demon Form",
    "Double Tap",
    "Exhume",
    "Feed",
    "Fiend Fire",
    "Immolate",
    "Impervious",
    "Juggernaut",
    "Limit Break",
    "Offering",
    "Reaper",
    "Bash+1",
    "Defend_R+1",
    "Strike_R+1",
    "Anger+1",
    "Armaments+1",
    "Body Slam+1",
    "Clash+1",
    "Cleave+1",
    "Clothesline+1",
    "Flex+1",
    "Havoc+1",
    "Headbutt+1",
    "Heavy Blade+1",
    "Iron Wave+1",
    "Perfected Strike+1",
    "Pommel Strike+1",
    "Shrug It Off+1",
    "Sword Boomerang+1",
    "Thunderclap+1",
    "True Grit+1",
    "Twin Strike+1",
    "Warcry+1",
    "Wild Strike+1",
    "Battle Trance+1",
    "Blood for Blood+1",
    "Bloodletting+1",
    "Burning Pact+1",
    "Carnage+1",
    "Combust+1",
    "Dark Embrace+1",
    "Disarm+1",
    "Dropkick+1",
    "Dual Wield+1",
    "Entrench+1",
    "Evolve+1",
    "Feel No Pain+1",
    "Fire Breathing+1",
    "Flame Barrier+1",
    "Ghostly Armor+1",
    "Hemokinesis+1",
    "Infernal Blade+1",
    "Inflame+1",
    "Intimidate+1",
    "Metallicize+1",
    "Power Through+1",
    "Pummel+1",
    "Rage+1",
    "Rampage+1",
    "Reckless Charge+1",
    "Rupture+1",
    "Searing Blow+1",
    "Second Wind+1",
    "Seeing Red+1",
    "Sentinel+1",
    "Sever Soul+1",
    "Shockwave+1",
    "Spot Weakness+1",
    "Uppercut+1",
    "Whirlwind+1",
    "Barricade+1",
    "Berserk+1",
    "Bludgeon+1",
    "Brutality+1",
    "Corruption+1",
    "Demon Form+1",
    "Double Tap+1",
    "Exhume+1",
    "Feed+1",
    "Fiend Fire+1",
    "Immolate+1",
    "Impervious+1",
    "Juggernaut+1",
    "Limit Break+1",
    "Offering+1",
    "Reaper+1",
]

colorless_cards = [
    "Bandage Up",
    "Blind",
    "Dark Shackles",
    "Deep Breath",
    "Discovery",
    "Dramatic Entrance",
    "Enlightenment",
    "Finesse",
    "Flash of Steel",
    "Forethought",
    "Good Instincts",
    "Impatience",
    "Jack of All Trades",
    "Madness",
    "Mind Blast",
    "Panacea",
    "Panic Button",
    "Purity",
    "Swift Strike",
    "Trip",
    "Apotheosis",
    "Chrysalis",
    "Hand of Greed",
    "Magnetism",
    "Master of Strategy",
    "Mayhem",
    "Metamorphosis",
    "Panache",
    "Sadistic Nature",
    "Secret Technique",
    "Secret Weapon",
    "The Bomb",
    "Thinking Ahead",
    "Transmutation",
    "Violence",
    "Apparition",
    "Become Almighty",
    "Beta",
    "Bite",
    "Expunger",
    "Fame and Fortune",
    "Insight",
    "J.A.X.",
    "Live Forever",
    "Miracle",
    "Omega",
    "Ritual Dagger",
    "Safety",
    "Shiv",
    "Smite",
    "Through Violence",
    "Bandage Up+1",
    "Blind+1",
    "Dark Shackles+1",
    "Deep Breath+1",
    "Discovery+1",
    "Dramatic Entrance+1",
    "Enlightenment+1",
    "Finesse+1",
    "Flash of Steel+1",
    "Forethought+1",
    "Good Instincts+1",
    "Impatience+1",
    "Jack of All Trades+1",
    "Madness+1",
    "Mind Blast+1",
    "Panacea+1",
    "Panic Button+1",
    "Purity+1",
    "Swift Strike+1",
    "Trip+1",
    "Apotheosis+1",
    "Chrysalis+1",
    "Hand of Greed+1",
    "Magnetism+1",
    "Master of Strategy+1",
    "Mayhem+1",
    "Metamorphosis+1",
    "Panache+1",
    "Sadistic Nature+1",
    "Secret Technique+1",
    "Secret Weapon+1",
    "The Bomb+1",
    "Thinking Ahead+1",
    "Transmutation+1",
    "Violence+1",
    "Apparition+1",
    "Become Almighty+1",
    "Beta+1",
    "Bite+1",
    "Expunger+1",
    "Fame and Fortune+1",
    "Insight+1",
    "J.A.X.+1",
    "Live Forever+1",
    "Miracle+1",
    "Omega+1",
    "Ritual Dagger+1",
    "Safety+1",
    "Shiv+1",
    "Smite+1",
    "Through Violence+1",
]

curse_cards = [
    "Clumsy",
    "Decay",
    "Doubt",
    "Injury",
    "Normality",
    "Pain",
    "Parasite",
    "Regret",
    "Shame",
    "Writhe",
    "AscendersBane",
    "Curse of the Bell",
    "Necronomicurse",
    "Pride"
]

AVAILABLE_RELICS = [
    "Enchiridion",
    "Happy Flower",
    "Torii",
    "Magic Flower",
    "Bag of Marbles",
    "Toxic Egg 2",
    "HandDrill",
    "Bag of Preparation",
    "Pocketwatch",
    "Ice Cream",
    "Oddly Smooth Stone",
    "Chemical X",
    "Self Forming Clay",
    "Sundial",
    "Lantern",
    "Paper Frog",
    "Runic Pyramid",
    "Tiny Chest",
    "Champion Belt",
    "Black Star",
    "Necronomicon",
    "Smiling Mask",
    "Red Skull",
    "Ectoplasm",
    "Runic Dome",
    "Molten Egg 2",
    "Peace Pipe",
    "Charon's Ashes",
    "NlothsMask",
    "Coffee Dripper",
    "Velvet Choker",
    "TungstenRod",
    "Blue Candle",
    "War Paint",
    "Centennial Puzzle",
    "GremlinMask",
    "Thread and Needle",
    "StoneCalendar",
    "Dead Branch",
    "TheAbacus",
    "Vajra",
    "WingedGreaves",
    "Nilry's Codex",
    "CaptainsWheel",
    "Circlet",
    "Mango",
    "Girya",
    "Bloody Idol",
    "Unceasing Top",
    "Dream Catcher",
    "Cursed Key",
    "Medical Kit",
    "SlaversCollar",
    "Blood Vial",
    "Snack Pack",
    "CeramicFish",
    "Regal Pillow",
    "Old Coin",
    "Runic Cube",
    "Kunai",
    "Snecko Eye",
    "Mummified Hand",
    "Odd Mushroom",
    "Mercury Hourglass",
    "Ancient Tea Set",
    "Bird Faced Urn",
    "Frozen Egg 2",
    "Potion Belt",
    "Ornamental Fan",
    "Anchor",
    "Bottled Tornado",
    "Bottled Lightning",
    "Dodecahedron",
    "Lizard Tail",
    "Mark of the Bloom",
    "Cauldron",
    "Red Mask",
    "Spirit Poop",
    "FaceOfCleric",
    "Burning Blood",
    "Empty Cage",
    "Calipers",
    "ClockworkSouvenir",
    "WarpedTongs",
    "Calling Bell",
    "HornCleat",
    "White Beast Statue",
    "Shovel",
    "Eternal Feather",
    "Frozen Eye",
    "Meat on the Bone",
    "MutagenicStrength",
    "Gambling Chip",
    "Juzu Bracelet",
    "Letter Opener",
    "NeowsBlessing",
    "MealTicket",
    "Ring of Hypnosis",
    "Boot",
    "Art of War",
    "Nloth's Gift",
    "Golden Idol",
    "Black Blood",
    "CultistMask",
    "Toolbox",
    "FossilizedHelix",
    "Pear",
    "Gremlin Horn",
    "Nunchaku",
    "Tiny House",
    "Strange Spoon",
    "The Courier",
    "Pantograph",
    "Sozu",
    "DollysMirror",
    "Matryoshka",
    "Question Card",
    "Prayer Wheel",
    "Fusion Hammer",
    "PreservedInsect",
    "Busted Crown",
    "SacredBark",
    "InkBottle",
    "Sling",
    "Bronze Scales",
    "MawBank",
    "Akabeko",
    "Lee's Waffle",
    "Toy Ornithopter",
    "Ginger",
    "Pen Nib",
    "Pandora's Box",
    "Turnip",
    "Strawberry",
    "Membership Card",
    "Astrolabe",
    "Omamori",
    "SsserpentHead",
    "Darkstone Periapt",
    "Incense Burner",
    "Brimstone",
    "StrikeDummy",
    "Bottled Flame",
    "Whetstone",
    "OrangePellets",
    "Shuriken",
    "Mark of Pain",
    "Singing Bowl",
    "Orrery",
    "Philosopher's Stone",
    "Du-Vu Doll",
    "Orichalcum"
]

AVAILABLE_CARDS = ironclad_cards + colorless_cards
