ironclad_cards = [
    "Bash",
    "Defend_R",
    "Strike_R",
    "Anger",
    "Armaments",
    "Body Slam",
    "Clash",
    "Cleave",
    "Clothesline",
    "Flex",
    "Havoc",
    "Headbutt",
    "Heavy Blade",
    "Iron Wave",
    "Perfected Strike",
    "Pommel Strike",
    "Shrug It Off",
    "Sword Boomerang",
    "Thunderclap",
    "True Grit",
    "Twin Strike",
    "Warcry",
    "Wild Strike",
    "Battle Trance",
    "Blood for Blood",
    "Bloodletting",
    "Burning Pact",
    "Carnage",
    "Combust",
    "Dark Embrace",
    "Disarm",
    "Dropkick",
    "Dual Wield",
    "Entrench",
    "Evolve",
    "Feel No Pain",
    "Fire Breathing",
    "Flame Barrier",
    "Ghostly Armor",
    "Hemokinesis",
    "Infernal Blade",
    "Inflame",
    "Intimidate",
    "Metallicize",
    "Power Through",
    "Pummel",
    "Rage",
    "Rampage",
    "Reckless Charge",
    "Rupture",
    "Searing Blow",
    "Second Wind",
    "Seeing Red",
    "Sentinel",
    "Sever Soul",
    "Shockwave",
    "Spot Weakness",
    "Uppercut",
    "Whirlwind",
    "Barricade",
    "Berserk",
    "Bludgeon",
    "Brutality",
    "Corruption",
    "Demon Form",
    "Double Tap",
    "Exhume",
    "Feed",
    "Fiend Fire",
    "Immolate",
    "Impervious",
    "Juggernaut",
    "Limit Break",
    "Offering",
    "Reaper",
    "Bash+1",
    "Defend_R+1",
    "Strike_R+1",
    "Anger+1",
    "Armaments+1",
    "Body Slam+1",
    "Clash+1",
    "Cleave+1",
    "Clothesline+1",
    "Flex+1",
    "Havoc+1",
    "Headbutt+1",
    "Heavy Blade+1",
    "Iron Wave+1",
    "Perfected Strike+1",
    "Pommel Strike+1",
    "Shrug It Off+1",
    "Sword Boomerang+1",
    "Thunderclap+1",
    "True Grit+1",
    "Twin Strike+1",
    "Warcry+1",
    "Wild Strike+1",
    "Battle Trance+1",
    "Blood for Blood+1",
    "Bloodletting+1",
    "Burning Pact+1",
    "Carnage+1",
    "Combust+1",
    "Dark Embrace+1",
    "Disarm+1",
    "Dropkick+1",
    "Dual Wield+1",
    "Entrench+1",
    "Evolve+1",
    "Feel No Pain+1",
    "Fire Breathing+1",
    "Flame Barrier+1",
    "Ghostly Armor+1",
    "Hemokinesis+1",
    "Infernal Blade+1",
    "Inflame+1",
    "Intimidate+1",
    "Metallicize+1",
    "Power Through+1",
    "Pummel+1",
    "Rage+1",
    "Rampage+1",
    "Reckless Charge+1",
    "Rupture+1",
    "Searing Blow+1",
    "Second Wind+1",
    "Seeing Red+1",
    "Sentinel+1",
    "Sever Soul+1",
    "Shockwave+1",
    "Spot Weakness+1",
    "Uppercut+1",
    "Whirlwind+1",
    "Barricade+1",
    "Berserk+1",
    "Bludgeon+1",
    "Brutality+1",
    "Corruption+1",
    "Demon Form+1",
    "Double Tap+1",
    "Exhume+1",
    "Feed+1",
    "Fiend Fire+1",
    "Immolate+1",
    "Impervious+1",
    "Juggernaut+1",
    "Limit Break+1",
    "Offering+1",
    "Reaper+1",
]

colorless_cards = [
    "Bandage Up",
    "Blind",
    "Dark Shackles",
    "Deep Breath",
    "Discovery",
    "Dramatic Entrance",
    "Enlightenment",
    "Finesse",
    "Flash of Steel",
    "Forethought",
    "Good Instincts",
    "Impatience",
    "Jack of All Trades",
    "Madness",
    "Mind Blast",
    "Panacea",
    "Panic Button",
    "Purity",
    "Swift Strike",
    "Trip",
    "Apotheosis",
    "Chrysalis",
    "Hand of Greed",
    "Magnetism",
    "Master of Strategy",
    "Mayhem",
    "Metamorphosis",
    "Panache",
    "Sadistic Nature",
    "Secret Technique",
    "Secret Weapon",
    "The Bomb",
    "Thinking Ahead",
    "Transmutation",
    "Violence",
    "Apparition",
    "Become Almighty",
    "Beta",
    "Bite",
    "Expunger",
    "Fame and Fortune",
    "Insight",
    "J.A.X.",
    "Live Forever",
    "Miracle",
    "Omega",
    "Ritual Dagger",
    "Safety",
    "Shiv",
    "Smite",
    "Through Violence",
    "Bandage Up+1",
    "Blind+1",
    "Dark Shackles+1",
    "Deep Breath+1",
    "Discovery+1",
    "Dramatic Entrance+1",
    "Enlightenment+1",
    "Finesse+1",
    "Flash of Steel+1",
    "Forethought+1",
    "Good Instincts+1",
    "Impatience+1",
    "Jack of All Trades+1",
    "Madness+1",
    "Mind Blast+1",
    "Panacea+1",
    "Panic Button+1",
    "Purity+1",
    "Swift Strike+1",
    "Trip+1",
    "Apotheosis+1",
    "Chrysalis+1",
    "Hand of Greed+1",
    "Magnetism+1",
    "Master of Strategy+1",
    "Mayhem+1",
    "Metamorphosis+1",
    "Panache+1",
    "Sadistic Nature+1",
    "Secret Technique+1",
    "Secret Weapon+1",
    "The Bomb+1",
    "Thinking Ahead+1",
    "Transmutation+1",
    "Violence+1",
    "Apparition+1",
    "Become Almighty+1",
    "Beta+1",
    "Bite+1",
    "Expunger+1",
    "Fame and Fortune+1",
    "Insight+1",
    "J.A.X.+1",
    "Live Forever+1",
    "Miracle+1",
    "Omega+1",
    "Ritual Dagger+1",
    "Safety+1",
    "Shiv+1",
    "Smite+1",
    "Through Violence+1",
]

curse_cards = [
    "Clumsy",
    "Decay",
    "Doubt",
    "Injury",
    "Normality",
    "Pain",
    "Parasite",
    "Regret",
    "Shame",
    "Writhe",
    "AscendersBane",
    "Curse of the Bell",
    "Necronomicurse",
    "Pride"
]

AVAILABLE_RELICS = [
    "Burning Blood",
    "Akabeko",
    "Anchor",
    "Ancient Tea Set",
    "Art of War",
    "Bag of Marbles",
    "Bag of Preparations",
    "Blood Vial",
    "Bronze Scales",
    "Centennial Puzzle",
    "Ceramic Fish",
    "Dream Catcher",
    "Happy Flower",
    "Juzu Bracelet",
    "Lantern",
    "Maw Bank",
    "Meal Ticket",
    "Nunchaku",
    "Oddly Smooth Stone",
    "Omamori",
    "Orichalcum",
    "Pen Nib",
    "Potion Belt",
    "Preserved Insect",
    "Regal Pillow",
    "Smiling Mask",
    "Strawberry",
    "The Boot",
    "Tiny Chest",
    "Toy Ornithopter",
    "Vajra",
    "War Paint",
    "Whetstone",
    "Red Skull",
    "Blue Candle",
    "Bottled Flame",
    "Bottled Lightning",
    "Bottled Tornado",
    "Darkstone Periapt",
    "Eternal Feather",
    "Frozen Egg",
    "Gremlin Horn",
    "Horn Cleat",
    "Ink Bottle",
    "Kunai",
    "Letter Opener",
    "Matryoshka",
    "Meat on the Bone",
    "Mercury Hourglass",
    "Molten Egg",
    "Mummified Hand",
    "Ornamental Fan",
    "Pantograph",
    "Pear",
    "Question Card",
    "Shuriken",
    "Singing Bowl",
    "Strike Dummy",
    "Sundial",
    "The Courier",
    "Toxic Egg",
    "White Beast Statue",
    "Paper Phrog",
    "Self-Forming Clay",
    "Bird-Faced Urn",
    "Calipers",
    "Captain's Wheel",
    "Dead Branch",
    "Du-Vu Doll",
    "Fosslized Helix",
    "Gambling Chip",
    "Ginger",
    "Girya",
    "Ice Cream",
    "Incense Burner",
    "Lizard Tail",
    "Mango",
    "Old Coin",
    "Peace Pipe",
    "Pocketwatch",
    "Prayer Wheel",
    "Shovel",
    "Stone Calendar",
    "Thread and Needle",
    "Torii",
    "Tungsten Rod",
    "Turnip",
    "Unceasing Top",
    "Wing Boots",
    "Champion Belt",
    "Charon's Ashes",
    "Magic Flower",
    "Cauldron",
    "Chemical X",
    "Clockwork Souvenir",
    "Dolly's Mirror",
    "Frozen Eye",
    "Hand Drill",
    "Lee's Waffle",
    "Medical Kit",
    "Membership Card",
    "Orange Pellets",
    "Orrery",
    "Sling of Courage",
    "Strange Spoon",
    "The Abacus",
    "Toolbox",
    "Brimstone",
    "Astrolabe",
    "Black Star",
    "Busted Crown",
    "Calling Bell",
    "Coffee Dripper",
    "Cursed Key",
    "Ectoplasm",
    "Empty Cage",
    "Fusion Hammer",
    "Pandora's Box",
    "Philosopher's Stone",
    "Runic Dome",
    "Runic Pyramid",
    "Sacred Bark",
    "Slaver's Collar",
    "Snecko Eye",
    "Sozu",
    "Tiny House",
    "Velvet Choker",
    "Black Blood",
    "Mark of Pain",
    "Runic Cube",
    "Bloody Idol",
    "Cultist Headpiece",
    "Enchiridion",
    "Face of Cleric",
    "Golden Idol",
    "Gremlin Visage",
    "Mark of the Bloom",
    "Mutagenic Strength",
    "N'loth's Gift",
    "N'loth's Hungry Face",
    "Necronomicon",
    "Neow's Lament",
    "Nilry's Codex",
    "Odd Mushroom",
    "Red Mask",
    "Spirit Poop",
    "Ssserpent Head",
    "Warped Tongs",
    "Circlet"
]

AVAILABLE_CARDS = ironclad_cards + colorless_cards
