ironclad_cards = [
    "Bash",
    "Defend_R",
    "Strike_R",
    "Anger",
    "Armaments",
    "Body Slam",
    "Clash",
    "Cleave",
    "Clothesline",
    "Flex",
    "Havoc",
    "Headbutt",
    "Heavy Blade"
    "Iron Wave"
    "Perfected Strike",
    "Pommel Strike",
    "Shrug It Off",
    "Sword Boomerang",
    "Thunderclap",
    "True Grit",
    "Twin Strike",
    "Warcry",
    "Wild Strike",
    "Battle Trance",
    "Blood for Blood",
    "Bloodletting",
    "Burning Pact",
    "Carnage",
    "Combust",
    "Dark Embrace",
    "Disarm",
    "Dropkick",
    "Dual Wield",
    "Entrench",
    "Evolve",
    "Feel No Pain",
    "Fire Breathing",
    "Flame Barrier",
    "Ghostly Armor",
    "Hemokinesis",
    "Infernal Blade",
    "Inflame",
    "Intimidate",
    "Metallicize",
    "Power Through",
    "Pummel",
    "Rage",
    "Rampage",
    "Reckless Charge",
    "Rupture",
    "Searing Blow",
    "Second Wind",
    "Seeing Red",
    "Sentinel",
    "Sever Soul",
    "Shockwave",
    "Spot Weakness",
    "Uppercut",
    "Whirlwind",
    "Barricade",
    "Berserk",
    "Bludgeon",
    "Brutality",
    "Corruption",
    "Demon Form",
    "Double Tap",
    "Exhume",
    "Feed",
    "Fiend Fire",
    "Immolate",
    "Impervious",
    "Juggernaut",
    "Limit Break",
    "Offering",
    "Reaper",
]

colorless_cards = [
    "Bandage Up",
    "Blind",
    "Dark Shackles",
    "Deep Breath",
    "Discovery",
    "Dramatic Entrance",
    "Enlightenment",
    "Finesse",
    "Flash of Steel",
    "Forethought",
    "Good Instincts",
    "Impatience",
    "Jack of All Trades",
    "Madness",
    "Mind Blast",
    "Panacea",
    "Panic Button",
    "Purity",
    "Swift Strike",
    "Trip",
    "Apotheosis",
    "Chrysalis",
    "Hand of Greed",
    "Magnetism",
    "Master of Strategy",
    "Mayhem",
    "Metamorphosis",
    "Panache",
    "Sadistic Nature",
    "Secret Technique",
    "Secret Weapon",
    "The Bomb",
    "Thinking Ahead",
    "Transmutation",
    "Violence",
    "Apparition",
    "Become Almighty",
    "Beta",
    "Bite",
    "Expunger",
    "Fame and Fortune",
    "Insight",
    "J.A.X.",
    "Live Forever",
    "Miracle",
    "Omega",
    "Ritual Dagger",
    "Safety",
    "Shiv",
    "Smite",
    "Through Violence"
]

curse_cards = [
    "Clumsy",
    "Decay",
    "Doubt",
    "Injury",
    "Normality",
    "Pain",
    "Parasite",
    "Regret",
    "Shame",
    "Writhe",
    "Ascender's Bane",
    "Curse of the Bell",
    "Necronomicurse",
    "Pride"
]